# Template Configuration
project:
  name: "{{PROJECT_NAME}}"
  description: "{{PROJECT_DESCRIPTION}}"
  owner: "{{OWNER_NAME}}"
  email: "{{CONTACT_EMAIL}}"
  security_email: "{{SECURITY_EMAIL}}"
  support_email: "{{SUPPORT_EMAIL}}"
  repo_url: "{{REPO_URL}}"
  documentation_url: "{{DOCS_URL}}"
  license: "{{LICENSE_TYPE}}"
  license_url: "{{LICENSE_URL}}"
  main_branch: "{{MAIN_BRANCH}}"
  year: "{{CURRENT_YEAR}}"

links:
  contributing: "{{CONTRIBUTING_PATH}}"
  code_of_conduct: "{{COC_PATH}}"
  security: "{{SECURITY_PATH}}"
  support: "{{SUPPORT_PATH}}"
  changelog: "{{CHANGELOG_PATH}}"
  license: "{{LICENSE_PATH}}"

badges:
  enabled: true
  custom:
    - name: "{{BADGE_NAME}}"
      image: "{{BADGE_IMAGE_URL}}"
      link: "{{BADGE_LINK_URL}}"

social:
  twitter: "{{TWITTER_HANDLE}}"
  discord: "{{DISCORD_INVITE}}"
  slack: "{{SLACK_INVITE}}"
  forum: "{{FORUM_URL}}"
